// lib/tools.ts

export type Tool = {
    slug: string;
    title: string;
    short: string;
    long: string;
    category: string;
    keywords: string[];
    ogImage?: string;
};

export const tools: Tool[] = [
    // --- Existing Tools (for context, not modified) ---

    {
        slug: "image-compressor",
        title: "Free Image Compressor Online",
        short: "Compress JPG, PNG, WEBP images online without losing quality. Fast, secure, and free.",
        long: "This free online image compressor helps you reduce image size without losing visible quality. Perfect for web developers, designers, and anyone looking to optimize images for faster loading websites. Supports JPG, PNG, and WebP formats with smart compression powered by modern algorithms.",
        category: "Image Tools",
        keywords: ["image compressor", "compress image online", "reduce image size", "jpg compressor", "png compressor"],
        ogImage: "/og/image-compressor.png",
    },
    {
        slug: "background-remover",
        title: "AI Background Remover",
        short: "Remove image backgrounds instantly using AI. Supports photos, products, and portraits.",
        long: "An AI-powered tool to remove image backgrounds in seconds. Upload any photo and get a clean, transparent PNG with professional-quality cutouts. Great for eCommerce, profile photos, and design work.",
        category: "Image Tools",
        keywords: ["background remover", "remove bg", "ai remove background"],
        ogImage: "/og/background-remover.png",
    },
    {
        slug: "pdf-merge",
        title: "Merge PDF Files Online",
        short: "Combine multiple PDFs into one file. Fast, simple, and secure.",
        long: "Easily merge multiple PDF files into a single document. This tool runs securely in the cloud, ensuring your files are never stored and always deleted after processing.",
        category: "PDF Tools",
        keywords: ["merge pdf", "combine pdf", "pdf joiner"],
        ogImage: "/og/pdf-merge.png",
    },
    {
        slug: "pdf-to-word",
        title: "Convert PDF to Word Online",
        short: "Convert PDFs to editable Word documents (DOCX) with high accuracy.",
        long: "Instantly convert your PDF files to Word documents. Maintains layout, formatting, and fonts. Perfect for editing scanned or digital PDFs.",
        category: "PDF Tools",
        keywords: ["pdf to word", "convert pdf", "pdf converter"],
        ogImage: "/og/pdf-to-word.png",
    },
    {
        slug: "qr-generator",
        title: "QR Code Generator",
        short: "Create QR codes for URLs, text, WiFi, and more.",
        long: "A fast and customizable QR code generator. Create QR codes for links, text, emails, phone numbers, or WiFi access. Supports high-resolution PNG downloads.",
        category: "Utility Tools",
        keywords: ["qr generator", "qr code", "make qr"],
        ogImage: "/og/qr-generator.png",
    },
    {
        slug: "image-converter",
        title: "Image Converter Online (JPG, PNG, WEBP)",
        short: "Convert images between JPG, PNG, and WEBP formats easily and quickly online.",
        long: "Use our free online **Image Converter** to change file formats instantly. Convert **JPG to PNG**, **PNG to WEBP**, or any other combination. Simple, fast, and maintains image quality. Essential for web optimization and design workflows.",
        category: "Image Tools",
        keywords: ["image converter", "jpg to png", "png to webp", "convert image format", "free image converter"],
        ogImage: "/og/image-converter.png",
    },
    {
        slug: "image-resizer",
        title: "Free Image Resizer Online",
        short: "Resize images by pixels or percentage for social media, email, or web use.",
        long: "Quickly resize your photos and images online. Adjust dimensions by setting custom **width and height** in pixels, or scale by a percentage. Perfect for creating images for social media, websites, and email attachments without installing software.",
        category: "Image Tools",
        keywords: ["image resizer", "resize image online", "photo resizer", "resize by pixel", "change image size"],
        ogImage: "/og/image-resizer.png",
    },
    {
        slug: "image-cropper",
        title: "Crop Image Online for Free",
        short: "Crop, cut, and trim photos to specific aspect ratios or custom dimensions online.",
        long: "Easily crop your images to focus on the perfect area. Use preset aspect ratios for social platforms (e.g., 1:1, 16:9) or define custom dimensions. Our tool provides precise control for cutting photos online.",
        category: "Image Tools",
        keywords: ["image cropper", "crop image online", "cut photo", "trim image", "free photo cropper"],
        ogImage: "/og/image-cropper.png",
    },
    {
        slug: "image-upscaler-ai",
        title: "AI Image Upscaler & Enlarger",
        short: "Enlarge images up to 4x using AI without losing quality. Perfect for low-resolution photos.",
        long: "The ultimate **AI Image Upscaler** to increase the resolution of your photos. Our advanced algorithms upscale images up to 4x, adding detail and sharpness while avoiding pixelation. Bring old or small photos back to life.",
        category: "Image Tools",
        keywords: ["image upscaler", "ai upscaler", "enlarge image without losing quality", "upscale photo", "4x image upscaler"],
        ogImage: "/og/image-upscaler-ai.png",
    },
    {
        slug: "photo-enhancer-ai",
        title: "AI Photo Enhancer Online",
        short: "Instantly enhance photo quality, fix colors, and improve details with artificial intelligence.",
        long: "Use our **AI Photo Enhancer** to automatically improve the quality of your images. Correct poor lighting, enhance colors, sharpen blurry photos, and restore details with a single click. Ideal for professional and personal photo edits.",
        category: "Image Tools",
        keywords: ["photo enhancer ai", "enhance photo quality", "fix blurry photos", "improve image quality", "ai photo restoration"],
        ogImage: "/og/photo-enhancer-ai.png",
    },
    {
        slug: "blur-background",
        title: "Blur Photo Background Online",
        short: "Apply a professional-looking blur effect to your image background for a portrait look.",
        long: "Create a beautiful **depth of field** or **bokeh effect** by blurring the background of your photo. Our tool automatically detects the subject and applies a soft blur, making your portraits and product shots stand out. Achieve a professional look instantly.",
        category: "Image Tools",
        keywords: ["blur background", "blur photo online", "bokeh effect", "background blur", "depth of field photo"],
        ogImage: "/og/blur-background.png",
    },
    {
        slug: "remove-watermark-ai",
        title: "AI Watermark Remover Tool",
        short: "Remove unwanted watermarks, logos, or text from images using smart AI technology.",
        long: "Intelligently remove watermarks and unwanted objects from your photos. Our **AI Watermark Remover** seamlessly fills the gaps, restoring the image area beneath the mark. Note: Only use on images you own and have permission to modify.",
        category: "Image Tools",
        keywords: ["remove watermark ai", "watermark remover", "delete logo from image", "ai object removal", "get rid of watermark"],
        ogImage: "/og/remove-watermark-ai.png",
    },
    {
        slug: "convert-to-webp",
        title: "Convert to WebP Online",
        short: "Convert JPG, PNG, and other image formats to the highly optimized WebP format.",
        long: "Boost your website speed by converting your images to **WebP**. This modern format provides superior compression and quality compared to JPG and PNG. Use our free tool for fast, lossy or lossless conversion to WebP.",
        category: "Image Tools",
        keywords: ["convert to webp", "jpg to webp", "png to webp", "webp converter", "optimize images webp"],
        ogImage: "/og/convert-to-webp.png",
    },

    // 📝 Document / PDF Tools
    {
        slug: "word-to-pdf",
        title: "Word to PDF Converter Online",
        short: "Convert Microsoft Word documents (DOCX, DOC) to PDF format easily and accurately.",
        long: "Instantly convert your **Word to PDF** files while preserving the original layout, formatting, and fonts. Ensures your document looks exactly as intended when shared or printed. Supports DOC and DOCX files.",
        category: "PDF Tools",
        keywords: ["word to pdf", "convert docx to pdf", "doc to pdf", "microsoft word to pdf converter", "free word to pdf"],
        ogImage: "/og/word-to-pdf.png",
    },
    {
        slug: "ppt-to-pdf",
        title: "PPT to PDF Converter Online",
        short: "Convert PowerPoint presentations (PPT, PPTX) into universally viewable PDF files.",
        long: "Easily convert your **PowerPoint slides to PDF** documents. A PDF file ensures your presentation looks correct on any device without needing the original software. Supports PPT and PPTX formats.",
        category: "PDF Tools",
        keywords: ["ppt to pdf", "powerpoint to pdf", "convert pptx to pdf", "pdf from powerpoint", "free ppt to pdf"],
        ogImage: "/og/ppt-to-pdf.png",
    },
    {
        slug: "excel-to-pdf",
        title: "Excel to PDF Converter Online",
        short: "Convert Excel spreadsheets (XLS, XLSX) into professional, static PDF documents.",
        long: "Transform your Excel data tables and charts into an easy-to-share **PDF** format. Ensures consistent viewing across all devices, maintaining cell layout and formatting. Supports XLS and XLSX files.",
        category: "PDF Tools",
        keywords: ["excel to pdf", "convert xlsx to pdf", "spreadsheet to pdf", "pdf from excel", "free excel to pdf"],
        ogImage: "/og/excel-to-pdf.png",
    },
    {
        slug: "pdf-split",
        title: "Split PDF Files Online",
        short: "Extract pages or split a large PDF document into multiple smaller files.",
        long: "Need to separate a multi-page document? Use our **PDF Splitter** to easily extract specific pages or divide the file into individual chapter files. Fast, secure, and perfect for organizing large PDF reports.",
        category: "PDF Tools",
        keywords: ["split pdf", "pdf splitter", "extract pages from pdf", "separate pdf pages", "divide pdf"],
        ogImage: "/og/pdf-split.png",
    },
    {
        slug: "pdf-rotate",
        title: "Rotate PDF Pages Online",
        short: "Rotate specific pages or the entire PDF document 90, 180, or 270 degrees.",
        long: "Fix misoriented pages in your document with our **PDF Rotate** tool. Easily spin individual pages or the entire file clockwise or counter-clockwise (90°, 180°, 270°) to correct scanning errors.",
        category: "PDF Tools",
        keywords: ["rotate pdf", "rotate pdf pages", "pdf rotator", "turn pdf 90 degrees"],
        ogImage: "/og/pdf-rotate.png",
    },
    {
        slug: "pdf-unlock",
        title: "Unlock PDF (Remove Password)",
        short: "Remove password protection from PDF files for easy viewing and editing.",
        long: "Securely use our **PDF Unlocker** to remove an unnecessary password from your document. You must know the original password to unlock the file. Convert restricted PDFs into easily accessible ones for printing and editing.",
        category: "PDF Tools",
        keywords: ["unlock pdf", "remove pdf password", "pdf password remover", "decrypt pdf", "free pdf unlocker"],
        ogImage: "/og/pdf-unlock.png",
    },
    {
        slug: "pdf-to-jpg",
        title: "Convert PDF to JPG Online",
        short: "Extract images or convert each page of a PDF into high-quality JPG files.",
        long: "Our **PDF to JPG converter** turns every page of your document into a separate, high-resolution image file. Perfect for sharing pages on social media or extracting image content from a PDF.",
        category: "PDF Tools",
        keywords: ["pdf to jpg", "convert pdf to image", "pdf to jpeg", "extract images from pdf", "free pdf to jpg"],
        ogImage: "/og/pdf-to-jpg.png",
    },
    {
        slug: "jpg-to-pdf",
        title: "Convert JPG to PDF Online",
        short: "Combine one or more JPG, JPEG, or PNG images into a single PDF document.",
        long: "Quickly convert your photos and images into a single, compact **PDF** file. Great for sending multiple images as one attachment. Supports JPG, JPEG, and PNG formats.",
        category: "PDF Tools",
        keywords: ["jpg to pdf", "image to pdf", "jpeg to pdf", "convert photos to pdf", "multiple images to pdf"],
        ogImage: "/og/jpg-to-pdf.png",
    },

    // ✍️ AI Writing Tools
    {
        slug: "ai-paragraph-generator",
        title: "AI Paragraph Generator Tool",
        short: "Instantly generate unique, high-quality paragraphs on any topic using AI.",
        long: "Stuck on a sentence? Our **AI Paragraph Generator** can create well-structured, coherent, and engaging paragraphs for essays, blog posts, or reports. Just input your topic and tone, and let the AI do the writing.",
        category: "AI Writing Tools",
        keywords: ["ai paragraph generator", "write paragraph with ai", "ai content writer", "automatic paragraph maker"],
        ogImage: "/og/ai-paragraph-generator.png",
    },
    {
        slug: "ai-blog-writer",
        title: "AI Blog Post Writer",
        short: "Generate full, SEO-optimized blog articles and content outlines in minutes.",
        long: "Scale your content creation with our **AI Blog Writer**. Generate engaging introductions, section outlines, and full-length articles tailored to your audience and SEO keywords. Save hours on writing and ideation.",
        category: "AI Writing Tools",
        keywords: ["ai blog writer", "generate blog post", "seo blog writer", "ai content creation", "automatic article writer"],
        ogImage: "/og/ai-blog-writer.png",
    },
    {
        slug: "ai-email-writer",
        title: "AI Email Generator & Writer",
        short: "Compose professional emails for sales, support, and marketing instantly with AI.",
        long: "Never stare at a blank screen again. Our **AI Email Writer** crafts perfect subject lines and body copy for cold outreach, follow-ups, customer support, or internal communication. Choose your purpose and let the AI write a clear, concise message.",
        category: "AI Writing Tools",
        keywords: ["ai email writer", "email generator", "ai compose email", "business email writer", "sales email ai"],
        ogImage: "/og/ai-email-writer.png",
    },
    {
        slug: "ai-essay-writer",
        title: "AI Essay Writer for Students",
        short: "Generate structured and well-researched essays for academic purposes quickly.",
        long: "Need help structuring an assignment? Our **AI Essay Writer** provides outlines, thesis statements, and full-length drafts for various subjects and academic levels. Use it responsibly to overcome writer's block and refine your arguments.",
        category: "AI Writing Tools",
        keywords: ["ai essay writer", "generate essay with ai", "academic writing ai", "essay generator for students", "write my essay ai"],
        ogImage: "/og/ai-essay-writer.png",
    },
    {
        slug: "ai-product-description-generator",
        title: "AI Product Description Generator",
        short: "Create compelling, SEO-friendly product descriptions for your eCommerce store instantly.",
        long: "Boost your sales with persuasive descriptions crafted by our **AI Product Description Generator**. Convert product features into enticing benefits, optimize for search engines, and write copy for hundreds of products quickly.",
        category: "AI Writing Tools",
        keywords: ["ai product description generator", "ecommerce copywriter", "product description ai", "write product copy", "ai for shopify"],
        ogImage: "/og/ai-product-description-generator.png",
    },
    {
        slug: "ai-summarizer",
        title: "AI Text Summarizer Tool",
        short: "Quickly summarize long articles, reports, and text into key points or a short paragraph.",
        long: "Use our **AI Summarizer** to get the core information from any long document or webpage. Choose your desired length and let the artificial intelligence extract the most important sentences and concepts. Perfect for research and quick reading.",
        category: "AI Writing Tools",
        keywords: ["ai summarizer", "text summarizer", "summarize article", "ai extract key points", "online text summary"],
        ogImage: "/og/ai-summarizer.png",
    },

    // 🔧 Utility Tools
    {
        slug: "url-shortener",
        title: "Free URL Shortener & Link Clipper",
        short: "Shorten long URLs into clean, manageable links quickly and securely.",
        long: "Turn long, messy web addresses into short, shareable links. Our **URL Shortener** is fast, reliable, and perfect for social media, email, and print. Track your link clicks and monitor performance.",
        category: "Utility Tools",
        keywords: ["url shortener", "shorten link", "link clipper", "free url shortener", "make short link"],
        ogImage: "/og/url-shortener.png",
    },
    {
        slug: "uuid-generator",
        title: "UUID Generator Online (v1, v4, v5)",
        short: "Generate universally unique identifiers (UUIDs) of various versions (v1, v4, v5).",
        long: "A reliable tool for developers to generate standard **UUIDs** (Globally Unique Identifiers). Supports time-based (v1), random (v4), and name-based (v5) versions for unique object identification in systems and databases.",
        category: "Utility Tools",
        keywords: ["uuid generator", "guid generator", "v4 uuid", "generate unique id", "online guid tool"],
        ogImage: "/og/uuid-generator.png",
    },
    {
        slug: "lorem-ipsum-generator",
        title: "Lorem Ipsum Generator",
        short: "Generate placeholder text for design, prototyping, and layout mockups.",
        long: "The essential tool for designers and developers. Quickly generate standard **Lorem Ipsum** text in paragraphs, sentences, or word counts to fill content space in your mockups and prototypes before the final copy is ready.",
        category: "Utility Tools",
        keywords: ["lorem ipsum generator", "placeholder text", "dummy text", "generate filler text", "lorem ipsum online"],
        ogImage: "/og/lorem-ipsum-generator.png",
    },
    {
        slug: "password-generator",
        title: "Strong Password Generator",
        short: "Generate highly secure, random passwords with a mix of letters, numbers, and symbols.",
        long: "Create truly strong, unpredictable passwords to protect your accounts. Customize the length and inclusion of uppercase, lowercase, numbers, and symbols to meet any security requirement. Essential for online safety.",
        category: "Utility Tools",
        keywords: ["password generator", "strong password", "random password", "secure password", "create strong password"],
        ogImage: "/og/password-generator.png",
    },
    {
        slug: "text-case-converter",
        title: "Text Case Converter Online",
        short: "Convert text to UPPER CASE, lower case, Title Case, Sentence case, and more.",
        long: "Easily change the capitalization of your text. Convert any block of text to **Title Case**, **UPPERCASE**, **lowercase**, or **Sentence case** with a single click. Ideal for writers and editors correcting formatting errors.",
        category: "Utility Tools",
        keywords: ["text case converter", "convert to uppercase", "title case generator", "change text case", "sentence case online"],
        ogImage: "/og/text-case-converter.png",
    },
    {
        slug: "color-picker",
        title: "Online Color Picker Tool (Hex, RGB, HSL)",
        short: "Select colors and get Hex, RGB, and HSL codes instantly for web design.",
        long: "An essential utility for designers and developers. Use our **Color Picker** to select colors from a palette or input a code to convert between **Hex**, **RGB**, and **HSL** formats. Find the perfect shade for your project.",
        category: "Utility Tools",
        keywords: ["color picker", "hex to rgb", "online color picker", "html color codes", "color palette generator"],
        ogImage: "/og/color-picker.png",
    },
    {
        slug: "css-minifier",
        title: "CSS Minifier & Compressor Online",
        short: "Reduce CSS file size by removing whitespace and comments to speed up your website.",
        long: "Optimize your website's loading speed by using our **CSS Minifier**. It removes unnecessary characters like spaces, comments, and line breaks without affecting code functionality, resulting in smaller file sizes.",
        category: "Utility Tools",
        keywords: ["css minifier", "compress css", "minify css online", "css optimizer", "reduce css size"],
        ogImage: "/og/css-minifier.png",
    },
    {
        slug: "html-minifier",
        title: "HTML Minifier & Compressor Online",
        short: "Minify HTML code to reduce file size and improve website performance.",
        long: "Improve your page load times with our **HTML Minifier**. It strips out extra characters, including comments and whitespace, making your HTML code leaner and more efficient for faster transmission over the network.",
        category: "Utility Tools",
        keywords: ["html minifier", "compress html", "minify html online", "html optimizer", "reduce html size"],
        ogImage: "/og/html-minifier.png",
    },

    // 💱 Finance / Conversion Tools
    {
        slug: "currency-converter",
        title: "Live Currency Converter Online",
        short: "Convert major global currencies with up-to-the-minute exchange rates.",
        long: "Check current and historical exchange rates with our free **Currency Converter**. Supports hundreds of global currencies (USD, EUR, GBP, JPY, etc.) with real-time data updates. Essential for travel, finance, and international business.",
        category: "Finance / Conversion Tools",
        keywords: ["currency converter", "live exchange rates", "usd to eur", "global currency converter", "forex converter"],
        ogImage: "/og/currency-converter.png",
    },
    {
        slug: "loan-calculator",
        title: "Free Loan Calculator (EMI)",
        short: "Calculate monthly payments (EMI), total interest, and amortization for any loan.",
        long: "Use our **Loan Calculator** to determine your **Equated Monthly Installment (EMI)**, total interest payable, and the full payment schedule. Perfect for estimating payments for mortgages, car loans, or personal loans.",
        category: "Finance / Conversion Tools",
        keywords: ["loan calculator", "emi calculator", "monthly payment calculator", "mortgage calculator", "loan amortization"],
        ogImage: "/og/loan-calculator.png",
    },
    {
        slug: "age-calculator",
        title: "Age Calculator Online (Date of Birth)",
        short: "Calculate a person's age accurately in years, months, and days from their birth date.",
        long: "Find out your exact age or the age difference between two dates. Our **Age Calculator** provides the result in years, months, days, hours, and minutes. Simple and fun for checking milestones.",
        category: "Finance / Conversion Tools",
        keywords: ["age calculator", "calculate age from dob", "date of birth calculator", "age in years months days"],
        ogImage: "/og/age-calculator.png",
    },
    {
        slug: "bmi-calculator",
        title: "BMI Calculator (Body Mass Index)",
        short: "Calculate your Body Mass Index (BMI) to assess your weight status.",
        long: "Determine your **Body Mass Index (BMI)** based on your height and weight. Use this health tool to check if you are underweight, normal weight, overweight, or obese. Available for standard and metric units.",
        category: "Finance / Conversion Tools",
        keywords: ["bmi calculator", "body mass index", "calculate bmi online", "healthy weight calculator", "bmi chart"],
        ogImage: "/og/bmi-calculator.png",
    },
    {
        slug: "unit-converter",
        title: "All-in-One Unit Converter",
        short: "Convert units for length, weight, temperature, volume, and more instantly.",
        long: "The comprehensive **Unit Converter** handles conversions for virtually every measurement type: **Length** (meters to feet), **Weight** (kg to lbs), **Temperature** (Celsius to Fahrenheit), **Volume**, and more. A crucial tool for science, engineering, and daily life.",
        category: "Finance / Conversion Tools",
        keywords: ["unit converter", "convert measurements", "length converter", "weight converter", "temperature converter", "metric to imperial"],
        ogImage: "/og/unit-converter.png",
    },

    // 🌐 SEO & Website Tools
    {
        slug: "meta-tag-generator",
        title: "SEO Meta Tag Generator",
        short: "Create perfect Meta Title, Meta Description, and robot tags for SEO.",
        long: "Use our free **Meta Tag Generator** to create the essential HTML tags that search engines like Google use to understand your content. Craft compelling meta descriptions and titles to improve your **Click-Through Rate (CTR)** and SEO ranking.",
        category: "SEO & Website Tools",
        keywords: ["meta tag generator", "seo meta tags", "meta description generator", "title tag generator", "html meta tags"],
        ogImage: "/og/meta-tag-generator.png",
    },
    {
        slug: "open-graph-generator",
        title: "Open Graph Meta Tag Generator",
        short: "Generate Open Graph (OG) tags for perfect social media sharing on platforms like Facebook and Twitter.",
        long: "Ensure your links look professional when shared on social media. Our **Open Graph Generator** creates the `<meta property='og:...' />` tags that control the title, description, and image displayed on platforms like Facebook, Twitter (X), and LinkedIn.",
        category: "SEO & Website Tools",
        keywords: ["open graph generator", "og tags", "social media meta tags", "facebook open graph", "twitter card generator"],
        ogImage: "/og/open-graph-generator.png",
    },
    {
        slug: "sitemap-generator",
        title: "XML Sitemap Generator Online",
        short: "Create a standard XML sitemap for your website to help search engines crawl your pages.",
        long: "A crucial SEO tool. Our **Sitemap Generator** automatically creates an XML file listing all the URLs on your site. This helps Google and other search engines discover and index your content more efficiently.",
        category: "SEO & Website Tools",
        keywords: ["xml sitemap generator", "create sitemap online", "html sitemap generator", "website sitemap tool", "seo sitemap"],
        ogImage: "/og/sitemap-generator.png",
    },
    {
        slug: "robots-txt-generator",
        title: "Robots.txt Generator Tool",
        short: "Create a perfect robots.txt file to manage search engine crawler access to your site.",
        long: "Generate a compliant **robots.txt** file to guide search engine bots. Use this tool to tell crawlers which parts of your site they can and cannot access, preventing indexing of private or redundant pages, which is vital for SEO.",
        category: "SEO & Website Tools",
        keywords: ["robots.txt generator", "create robots txt file", "seo robots txt", "disallow crawler"],
        ogImage: "/og/robots-txt-generator.png",
    },
    {
        slug: "website-screenshot",
        title: "Website Screenshot Generator (API)",
        short: "Capture a full-page, high-resolution screenshot of any website instantly.",
        long: "Need a high-quality image of a webpage? Our tool uses a powerful API to capture a full-page screenshot of any URL, perfect for design review, presentations, or documentation. Get an accurate, non-cached view.",
        category: "SEO & Website Tools",
        keywords: ["website screenshot", "full page screenshot", "capture website image", "api screenshot tool", "url to image"],
        ogImage: "/og/website-screenshot.png",
    },
    {
        slug: "whois-lookup",
        title: "Whois Domain Lookup Tool",
        short: "Find the registrar, owner, registration date, and contact info for any domain name.",
        long: "Perform a **Whois Lookup** to check the public registration records for any domain name. Discover who owns a website, when it was registered, and its expiration date. Essential for domain investors and researchers.",
        category: "SEO & Website Tools",
        keywords: ["whois lookup", "domain lookup", "whois checker", "find domain owner", "check domain registration"],
        ogImage: "/og/whois-lookup.png",
    },
    {
        slug: "dns-lookup",
        title: "DNS Lookup Tool Online",
        short: "Check DNS records (A, CNAME, MX, TXT) for any domain name instantly.",
        long: "Use our **DNS Lookup** tool to diagnose domain name issues and verify record propagation. Check essential records like **A** (address), **CNAME** (alias), **MX** (mail exchange), and **TXT** (text) for troubleshooting and setup.",
        category: "SEO & Website Tools",
        keywords: ["dns lookup", "check dns records", "a record lookup", "cname lookup", "mx record checker", "dns propagation tool"],
        ogImage: "/og/dns-lookup.png",
    },
    {
        slug: "ip-checker",
        title: "IP Address Checker & Locator",
        short: "Find your public IP address and view detailed geolocation information.",
        long: "Instantly check your current public **IP address** and see its approximate **geolocation** (city, region, country, and ISP). Useful for network diagnostics, security, and VPN verification.",
        category: "SEO & Website Tools",
        keywords: ["ip checker", "what is my ip", "ip address lookup", "find my ip location", "public ip address"],
        ogImage: "/og/ip-checker.png",
    },
];

/**
 * Get a tool by slug
 */
export function getToolBySlug(slug: string): Tool | undefined {
    return tools.find((tool) => tool.slug === slug);
}

/**
 * Optional: return all tools by category
 */
export function getToolsByCategory(category: string): Tool[] {
    return tools.filter((tool) => tool.category === category);
}
