"use client"
import { AuthProvider } from "@/components/auth-provider";
import "./globals.css";
import Navber from "@/components/Navber";
import { Toaster } from "sonner";
import { Footer } from "@/components/homePage/Footer";
import { MusicProvider } from "@/providers/MusicProvider";
import ClickSoundProvider from "@/providers/ClickSoundProvider";





// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased font-Roboto `}
      >
        <MusicProvider>
          <AuthProvider>
            <Navber />
             <ClickSoundProvider />
            {children}
            <Toaster />
            <Footer />
          </AuthProvider>
        </MusicProvider>
      </body>
    </html>
  );
}
