import type { Metadata } from "next";
import "./globals.css";
import Navber from "@/components/Navber";
import Cursor from "@/components/Cousor";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased bg-slate-900 text-white font-Roboto `}
      >

        <Cursor></Cursor>
        <Navber></Navber>
        {children}
    
      </body>
    </html>
  );
}
