name: Deploy Next.js to EC2

on:
  push:
    branches:
      - main  # Trigger deploy only on main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH key
        uses: actions/ssh-action@v1.0.3
        with:
          host: ${{secrets.SSH_HOST}}
          username: root
          key: ${{secrets.SSH_KEY}}
          script: | 
            cd /home/ubuntu/reza/reza.dev-portfolio-website-nextJS-
            git pull 
            npm run build
            npm install
        